### ISSUE TITLE
xrpl-dev-portal/content/references/client-libraries.md の翻訳

### ISSUE THREAD

**Issue by mtmttksh** [xrpl-japan/xrpl-dev-portal#2]
ご確認ください(ファイル中の上段：原文、下段：訳文です)。
[client-libraries.ja.txt](https://github.com/xrpl-japan/xrpl-dev-portal/files/9160064/client-libraries.ja.txt)

それから、すみません、操作方法が分からない中で触って模索している中で、添付ワードに貼ったキャプチャで示した箇所に、翻訳したものを追加してしまいました。元に戻す方法が分からず、可能であれば削除いただけませんでしょうか。お手数おかけし申し訳ございません。よろしくお願いします。
[キャプチャ.docx](https://github.com/xrpl-japan/xrpl-dev-portal/files/9159976/default.docx)

**Comment by tequdev** [comment]
この形に翻訳しました。

---

---
html: client-libraries.html
parent: references.html
blurb: これらのライブラリを使用して、お好みのプログラミング言語からXRP Ledgerにアクセスします。
---
# クライアントライブラリ

これらのクライアントライブラリは、XRP Ledgerのデータにアクセスし処理するための一般的な作業の一部を簡素化し、それぞれのプログラミング言語のネイティブな規約に従った形でデータを表示します。

その他のプログラミング言語の場合、[HTTP APIs](http-websocket-apis.html) を通してXRP Ledgerにアクセスすることが可能です。

| 言語 | ライブラリ名 | Get Started | APIリファレンス | ソースコード |
|----------|--------------|-------------|---------------|-------------|
| **Python**   | `xrpl-py`      | [Get Started Using Python](get-started-using-python.html) | [API Reference](https://xrpl-py.readthedocs.io/) | [Repo](https://github.com/XRPLF/xrpl-py) |
| **JavaScript** / **TypeScript** | `xrpl.js` | [Get Started](get-started-using-javascript.html) |  [API Reference](https://js.xrpl.org/) | [Repo](https://github.com/XRPLF/xrpl.js) |
| **C++**      | `rippled` Signing Library | [Get Started](https://github.com/ripple/rippled/tree/develop/Builds/linux#signing-library) |  | (Part of [`rippled`](https://github.com/ripple/rippled/)) |
| **Java** | `xrpl4j` | [Get Started Using Java](get-started-using-java.html) | [API Reference](https://javadoc.io/doc/org.xrpl/)  | [Repo](https://github.com/XRPLF/xrpl4j) |
| **Ruby** | `xrbp` | | [API Reference](https://www.rubydoc.info/gems/xrbp) | [Repo](https://github.com/DevNullProd/xrbp) |

**ヒント:** ここに掲載されていないクライアントライブラリを追加するには、[このページの変更を提案]({{target.github_forkurl}}/edit/{{target.github_branch}}/content/{{currentpage.md}})してください！
