### ISSUE TITLE
xrpl-dev-portal/content/references/xrpapi.ja.md の翻訳

### ISSUE THREAD

**Issue by mtmttksh** [xrpl-japan/xrpl-dev-portal#3]
ご確認ください(ファイル中の上段：原文、下段：訳文)。
[xrpapi.ja.txt](https://github.com/xrpl-japan/xrpl-dev-portal/files/9160097/xrpapi.ja.txt)

**Comment by tequdev** [comment]
この形で作成しました

---

---
html: xrp-api.html
parent: references.html
blurb: XRP LedgerにRESTライクのインターフェイスを提供するAPIサーバ
template: pagetype-redirect.html.jinja
redirect_url: https://xpring-eng.github.io/xrp-api/
nav_omit: true
filters:
    - xrpapi_readme
---
# XRP-API

XRP-API サーバーは、XRP Ledger への REST ライクな代替インターフェースを提供しますが、現在安定したソフトウェアとは言えず、積極的なサポートは行っていません。
